version: '3.9'
services:
  test:
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    build: 
      context: .
      dockerfile: test/Dockerfile
    entrypoint: >
      /bin/sh -c "
      /bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /bin/mc mb myminio/test-bucket;
      go test ./...
      "
    depends_on:
      - minioConf
      - mongo
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minioConf:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/test-bucket;
      /usr/bin/mc mb myminio/test-bucket;
      exit 0;
      "
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test123